# generated by datamodel-codegen:
#   filename:  ActivityLevel.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from enum import Enum


class ActivityLevel(Enum):
    WEAK = "WEAK"
    GROWING = "GROWING"
    STRONG = "STRONG"
    RESTRICTED = "RESTRICTED"
