# generated by datamodel-codegen:
#   filename:  Chart.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AwareDatetime, BaseModel, Field

from . import WaypointSymbol


class Chart(BaseModel):
    waypointSymbol: Optional[WaypointSymbol] = None
    submittedBy: Optional[str] = Field(
        None,
        description="The agent that submitted the chart for this waypoint.",
    )
    submittedOn: Optional[AwareDatetime] = Field(
        None, description="The time the chart for this waypoint was submitted."
    )
