# generated by datamodel-codegen:
#   filename:  ConnectedSystem.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, constr

from . import SystemType


class ConnectedSystem(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description="The symbol of the system."
    )
    sectorSymbol: constr(min_length=1) = Field(
        ..., description="The sector of this system."
    )
    type: SystemType
    factionSymbol: Optional[str] = Field(
        None,
        description="The symbol of the faction that owns the connected jump gate in the system.",
    )
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
    distance: int = Field(
        ...,
        description="The distance of this system to the connected Jump Gate.",
    )
