# generated by datamodel-codegen:
#   filename:  Construction.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from . import ConstructionMaterial


class Construction(BaseModel):
    symbol: str = Field(..., description="The symbol of the waypoint.")
    materials: List[ConstructionMaterial] = Field(
        ..., description="The materials required to construct the waypoint."
    )
    isComplete: bool = Field(
        ..., description="Whether the waypoint has been constructed."
    )
