# generated by datamodel-codegen:
#   filename:  ConstructionMaterial.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import TradeSymbol


class ConstructionMaterial(BaseModel):
    tradeSymbol: TradeSymbol
    required: int = Field(..., description="The number of units required.")
    fulfilled: int = Field(
        ...,
        description="The number of units fulfilled toward the required amount.",
    )
