# generated by datamodel-codegen:
#   filename:  Construction.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from . import ConstructionMaterial


class Model(BaseModel):
    symbol: str = Field(..., description="The symbol of the waypoint.")
    materials: List[ConstructionMaterial.Model] = Field(
        ..., description="The materials required to construct the waypoint."
    )
    isComplete: bool = Field(
        ..., description="Whether the waypoint has been constructed."
    )
