# generated by datamodel-codegen:
#   filename:  ContractPayment.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    onAccepted: int = Field(
        ...,
        description="The amount of credits received up front for accepting the contract.",
    )
    onFulfilled: int = Field(
        ...,
        description="The amount of credits received when the contract is fulfilled.",
    )
