# generated by datamodel-codegen:
#   filename:  ContractDeliverGood.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class ContractDeliverGood(BaseModel):
    tradeSymbol: constr(min_length=1) = Field(
        ..., description="The symbol of the trade good to deliver."
    )
    destinationSymbol: constr(min_length=1) = Field(
        ..., description="The destination where goods need to be delivered."
    )
    unitsRequired: int = Field(
        ...,
        description="The number of units that need to be delivered on this contract.",
    )
    unitsFulfilled: int = Field(
        ..., description="The number of units fulfilled on this contract."
    )
