# generated by datamodel-codegen:
#   filename:  ContractTerms.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import AwareDatetime, BaseModel, Field

from . import ContractDeliverGood, ContractPayment


class Model(BaseModel):
    deadline: AwareDatetime = Field(
        ..., description="The deadline for the contract."
    )
    payment: ContractPayment.Model
    deliver: Optional[List[ContractDeliverGood.Model]] = Field(
        None,
        description="The cargo that needs to be delivered to fulfill the contract.",
    )
