# generated by datamodel-codegen:
#   filename:  Cooldown.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class Cooldown(BaseModel):
    shipSymbol: constr(min_length=1) = Field(
        ..., description="The symbol of the ship that is on cooldown"
    )
    totalSeconds: conint(ge=0) = Field(
        ..., description="The total duration of the cooldown in seconds"
    )
    remainingSeconds: conint(ge=0) = Field(
        ..., description="The remaining duration of the cooldown in seconds"
    )
    expiration: Optional[AwareDatetime] = Field(
        None,
        description="The date and time when the cooldown expires in ISO 8601 format",
    )
