# generated by datamodel-codegen:
#   filename:  ExtractionYield.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import TradeSymbol


class Model(BaseModel):
    symbol: TradeSymbol.Model
    units: int = Field(
        ...,
        description="The number of units extracted that were placed into the ship's cargo hold.",
    )
