# generated by datamodel-codegen:
#   filename:  Extraction.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr

from . import ExtractionYield


class Extraction(BaseModel):
    shipSymbol: constr(min_length=1) = Field(
        ..., description="Symbol of the ship that executed the extraction."
    )
    yield_: ExtractionYield = Field(..., alias="yield")
