# generated by datamodel-codegen:
#   filename:  ExtractionYield.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import TradeSymbol


class ExtractionYield(BaseModel):
    symbol: TradeSymbol
    units: int = Field(
        ...,
        description="The number of units extracted that were placed into the ship's cargo hold.",
    )
