# generated by datamodel-codegen:
#   filename:  FactionTrait.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import FactionTraitSymbol


class Model(BaseModel):
    symbol: FactionTraitSymbol.Model
    name: str = Field(..., description="The name of the trait.")
    description: str = Field(..., description="A description of the trait.")
