# generated by datamodel-codegen:
#   filename:  FactionTrait.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from .FactionTraitSymbol import FactionTraitSymbol


class FactionTrait(BaseModel):
    symbol: FactionTraitSymbol
    name: str = Field(..., description="The name of the trait.")
    description: str = Field(..., description="A description of the trait.")
