# generated by datamodel-codegen:
#   filename:  Faction.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr

from .FactionSymbol import FactionSymbol
from .FactionTrait import FactionTrait


class Faction(BaseModel):
    symbol: FactionSymbol
    name: constr(min_length=1) = Field(..., description="Name of the faction.")
    description: constr(min_length=1) = Field(
        ..., description="Description of the faction."
    )
    headquarters: Optional[constr(min_length=1)] = Field(
        None,
        description="The waypoint in which the faction's HQ is located in.",
    )
    traits: List[FactionTrait] = Field(
        ..., description="List of traits that define this faction."
    )
    isRecruiting: bool = Field(
        ...,
        description="Whether or not the faction is currently recruiting new agents.",
    )
