# generated by datamodel-codegen:
#   filename:  JumpGate.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from . import WaypointSymbol


class Model(BaseModel):
    symbol: WaypointSymbol.Model
    connections: List[str] = Field(
        ..., description="All the gates that are connected to this waypoint."
    )
