# generated by datamodel-codegen:
#   filename:  JumpGate.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from . import WaypointSymbol


class JumpGate(BaseModel):
    symbol: WaypointSymbol
    connections: List[str] = Field(
        ..., description="All the gates that are connected to this waypoint."
    )
