# generated by datamodel-codegen:
#   filename:  MarketTransaction.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, conint

from . import WaypointSymbol


class Type(Enum):
    PURCHASE = "PURCHASE"
    SELL = "SELL"


class Model(BaseModel):
    waypointSymbol: WaypointSymbol.Model
    shipSymbol: str = Field(
        ..., description="The symbol of the ship that made the transaction."
    )
    tradeSymbol: str = Field(..., description="The symbol of the trade good.")
    type: Type = Field(..., description="The type of transaction.")
    units: conint(ge=0) = Field(
        ..., description="The number of units of the transaction."
    )
    pricePerUnit: conint(ge=0) = Field(
        ..., description="The price per unit of the transaction."
    )
    totalPrice: conint(ge=0) = Field(
        ..., description="The total price of the transaction."
    )
    timestamp: AwareDatetime = Field(
        ..., description="The timestamp of the transaction."
    )
