# generated by datamodel-codegen:
#   filename:  ScannedWaypoint.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from . import (
    Chart,
    SystemSymbol,
    WaypointFaction,
    WaypointOrbital,
    WaypointSymbol,
    WaypointTrait,
    WaypointType,
)


class Model(BaseModel):
    symbol: WaypointSymbol.Model
    type: WaypointType.Model
    systemSymbol: SystemSymbol.Model
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
    orbitals: List[WaypointOrbital.Model] = Field(
        ..., description="List of waypoints that orbit this waypoint."
    )
    faction: Optional[WaypointFaction.Model] = None
    traits: List[WaypointTrait.Model] = Field(
        ..., description="The traits of the waypoint."
    )
    chart: Optional[Chart.Model] = None
