# generated by datamodel-codegen:
#   filename:  ScannedShip.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from .ShipNav import ShipNav
from .ShipRegistration import ShipRegistration


class Frame(BaseModel):
    symbol: str = Field(..., description="The symbol of the frame.")


class Reactor(BaseModel):
    symbol: str = Field(..., description="The symbol of the reactor.")


class Engine(BaseModel):
    symbol: str = Field(..., description="The symbol of the engine.")


class Mount(BaseModel):
    symbol: str = Field(..., description="The symbol of the mount.")


class ScannedShip(BaseModel):
    symbol: str = Field(
        ..., description="The globally unique identifier of the ship."
    )
    registration: ShipRegistration
    nav: ShipNav
    frame: Optional[Frame] = Field(None, description="The frame of the ship.")
    reactor: Optional[Reactor] = Field(
        None, description="The reactor of the ship."
    )
    engine: Engine = Field(..., description="The engine of the ship.")
    mounts: Optional[List[Mount]] = Field(
        None, description="List of mounts installed in the ship."
    )
