# generated by datamodel-codegen:
#   filename:  ScannedSystem.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr

from .SystemType import SystemType


class ScannedSystem(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description="Symbol of the system."
    )
    sectorSymbol: constr(min_length=1) = Field(
        ..., description="Symbol of the system's sector."
    )
    type: SystemType
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
    distance: int = Field(
        ..., description="The system's distance from the scanning ship."
    )
