# generated by datamodel-codegen:
#   filename:  ScannedSystem.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr

from . import SystemType


class Model(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description="Symbol of the system."
    )
    sectorSymbol: constr(min_length=1) = Field(
        ..., description="Symbol of the system's sector."
    )
    type: SystemType.Model
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
    distance: int = Field(
        ..., description="The system's distance from the scanning ship."
    )
