# generated by datamodel-codegen:
#   filename:  ScannedWaypoint.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from .Chart import Chart
from .SystemSymbol import SystemSymbol
from .WaypointFaction import WaypointFaction
from .WaypointOrbital import WaypointOrbital
from .WaypointSymbol import WaypointSymbol
from .WaypointTrait import WaypointTrait
from .WaypointType import WaypointType


class ScannedWaypoint(BaseModel):
    symbol: WaypointSymbol
    type: WaypointType
    systemSymbol: SystemSymbol
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
    orbitals: List[WaypointOrbital] = Field(
        ..., description="List of waypoints that orbit this waypoint."
    )
    faction: Optional[WaypointFaction] = None
    traits: List[WaypointTrait] = Field(
        ..., description="The traits of the waypoint."
    )
    chart: Optional[Chart] = None
