# generated by datamodel-codegen:
#   filename:  ScannedWaypoint.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from . import (
    Chart,
    SystemSymbol,
    WaypointFaction,
    WaypointOrbital,
    WaypointSymbol,
    WaypointTrait,
    WaypointType,
)


class ScannedWaypoint(BaseModel):
    symbol: WaypointSymbol
    type: WaypointType
    systemSymbol: SystemSymbol
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
    orbitals: List[WaypointOrbital] = Field(
        ..., description="List of waypoints that orbit this waypoint."
    )
    faction: Optional[WaypointFaction] = None
    traits: List[WaypointTrait] = Field(
        ..., description="The traits of the waypoint."
    )
    chart: Optional[Chart] = None
