# generated by datamodel-codegen:
#   filename:  ShipNav.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import (
    ShipNavFlightMode,
    ShipNavRoute,
    ShipNavStatus,
    SystemSymbol,
    WaypointSymbol,
)


class Model(BaseModel):
    systemSymbol: SystemSymbol.Model
    waypointSymbol: WaypointSymbol.Model
    route: ShipNavRoute.Model
    status: ShipNavStatus.Model
    flightMode: ShipNavFlightMode.Model
