# generated by datamodel-codegen:
#   filename:  ShipComponentCondition.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import Field, RootModel, confloat


class Model(RootModel[confloat(ge=0.0, le=1.0)]):
    root: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description="The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.",
    )
