# generated by datamodel-codegen:
#   filename:  ShipRegistration.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr

from .ShipRole import ShipRole


class ShipRegistration(BaseModel):
    name: constr(min_length=1) = Field(
        ..., description="The agent's registered name of the ship"
    )
    factionSymbol: constr(min_length=1) = Field(
        ...,
        description="The symbol of the faction the ship is registered with",
    )
    role: ShipRole
