# generated by datamodel-codegen:
#   filename:  ShipFuel.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AwareDatetime, BaseModel, Field, conint


class Consumed(BaseModel):
    amount: conint(ge=0) = Field(
        ...,
        description="The amount of fuel consumed by the most recent transit or action.",
    )
    timestamp: AwareDatetime = Field(
        ..., description="The time at which the fuel was consumed."
    )


class Model(BaseModel):
    current: conint(ge=0) = Field(
        ..., description="The current amount of fuel in the ship's tanks."
    )
    capacity: conint(ge=0) = Field(
        ...,
        description="The maximum amount of fuel the ship's tanks can hold.",
    )
    consumed: Optional[Consumed] = Field(
        None,
        description="An object that only shows up when an action has consumed fuel in the process. Shows the fuel consumption data.",
    )
