# generated by datamodel-codegen:
#   filename:  ShipyardShip.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from . import (
    ActivityLevel,
    ShipEngine,
    ShipFrame,
    ShipModule,
    ShipMount,
    ShipReactor,
    ShipType,
    SupplyLevel,
)


class Crew(BaseModel):
    required: int
    capacity: int


class ShipyardShip(BaseModel):
    type: ShipType
    name: str
    description: str
    supply: SupplyLevel
    activity: Optional[ActivityLevel] = None
    purchasePrice: int
    frame: ShipFrame
    reactor: ShipReactor
    engine: ShipEngine
    modules: List[ShipModule]
    mounts: List[ShipMount]
    crew: Crew
