# generated by datamodel-codegen:
#   filename:  ShipRequirements.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ShipRequirements(BaseModel):
    power: Optional[int] = Field(
        None, description="The amount of power required from the reactor."
    )
    crew: Optional[int] = Field(
        None, description="The number of crew required for operation."
    )
    slots: Optional[int] = Field(
        None,
        description="The number of module slots required for installation.",
    )
