# generated by datamodel-codegen:
#   filename:  ShipyardShip.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from .ActivityLevel import ActivityLevel
from .ShipEngine import ShipEngine
from .ShipFrame import ShipFrame
from .ShipModule import ShipModule
from .ShipMount import ShipMount
from .ShipReactor import ShipReactor
from .ShipType import ShipType
from .SupplyLevel import SupplyLevel


class Crew(BaseModel):
    required: int
    capacity: int


class ShipyardShip(BaseModel):
    type: ShipType
    name: str
    description: str
    supply: SupplyLevel
    activity: Optional[ActivityLevel] = None
    purchasePrice: int
    frame: ShipFrame
    reactor: ShipReactor
    engine: ShipEngine
    modules: List[ShipModule]
    mounts: List[ShipMount]
    crew: Crew
