# generated by datamodel-codegen:
#   filename:  ShipNavRouteWaypoint.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr

from . import SystemSymbol, WaypointType


class Model(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description="The symbol of the waypoint."
    )
    type: WaypointType.Model
    systemSymbol: SystemSymbol.Model
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
