# generated by datamodel-codegen:
#   filename:  ShipNav.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import (
    ShipNavFlightMode,
    ShipNavRoute,
    ShipNavStatus,
    SystemSymbol,
    WaypointSymbol,
)


class ShipNav(BaseModel):
    systemSymbol: SystemSymbol
    waypointSymbol: WaypointSymbol
    route: ShipNavRoute
    status: ShipNavStatus
    flightMode: ShipNavFlightMode
