# generated by datamodel-codegen:
#   filename:  ShipCargoItem.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint

from . import TradeSymbol


class ShipCargoItem(BaseModel):
    symbol: TradeSymbol
    name: str = Field(..., description="The name of the cargo item type.")
    description: str = Field(
        ..., description="The description of the cargo item type."
    )
    units: conint(ge=1) = Field(
        ..., description="The number of units of the cargo item."
    )
