# generated by datamodel-codegen:
#   filename:  ShipComponentQuality.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import Field, RootModel


class ShipComponentQuality(RootModel[float]):
    root: float = Field(
        ...,
        description="The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.",
        title="ShipComponentQuality",
    )
