# generated by datamodel-codegen:
#   filename:  ShipyardTransaction.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field, conint

from . import WaypointSymbol


class ShipyardTransaction(BaseModel):
    waypointSymbol: WaypointSymbol
    shipSymbol: str = Field(
        ...,
        description="The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction. Contrary to what the name implies, this is NOT the symbol of the ship that was purchased.",
    )
    shipType: str = Field(
        ...,
        description="The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction.",
    )
    price: conint(ge=0) = Field(
        ..., description="The price of the transaction."
    )
    agentSymbol: str = Field(
        ..., description="The symbol of the agent that made the transaction."
    )
    timestamp: AwareDatetime = Field(
        ..., description="The timestamp of the transaction."
    )
