# generated by datamodel-codegen:
#   filename:  Ship.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from .Cooldown import Cooldown
from .ShipCargo import ShipCargo
from .ShipCrew import ShipCrew
from .ShipEngine import ShipEngine
from .ShipFrame import ShipFrame
from .ShipFuel import ShipFuel
from .ShipModule import ShipModule
from .ShipMount import ShipMount
from .ShipNav import ShipNav
from .ShipReactor import ShipReactor
from .ShipRegistration import ShipRegistration


class Ship(BaseModel):
    symbol: str = Field(
        ...,
        description="The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`",
    )
    registration: ShipRegistration
    nav: ShipNav
    crew: ShipCrew
    frame: ShipFrame
    reactor: ShipReactor
    engine: ShipEngine
    cooldown: Cooldown
    modules: List[ShipModule] = Field(
        ..., description="Modules installed in this ship."
    )
    mounts: List[ShipMount] = Field(
        ..., description="Mounts installed in this ship."
    )
    cargo: ShipCargo
    fuel: ShipFuel
