# generated by datamodel-codegen:
#   filename:  Ship.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from . import (
    Cooldown,
    ShipCargo,
    ShipCrew,
    ShipEngine,
    ShipFrame,
    ShipFuel,
    ShipModule,
    ShipMount,
    ShipNav,
    ShipReactor,
    ShipRegistration,
)


class Ship(BaseModel):
    symbol: str = Field(
        ...,
        description="The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`",
    )
    registration: ShipRegistration
    nav: ShipNav
    crew: ShipCrew
    frame: ShipFrame
    reactor: ShipReactor
    engine: ShipEngine
    cooldown: Cooldown
    modules: List[ShipModule] = Field(
        ..., description="Modules installed in this ship."
    )
    mounts: List[ShipMount] = Field(
        ..., description="Mounts installed in this ship."
    )
    cargo: ShipCargo
    fuel: ShipFuel
