# generated by datamodel-codegen:
#   filename:  ShipyardShip.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from . import (
    ActivityLevel,
    ShipEngine,
    ShipFrame,
    ShipModule,
    ShipMount,
    ShipReactor,
    ShipType,
    SupplyLevel,
)


class Crew(BaseModel):
    required: int
    capacity: int


class Model(BaseModel):
    type: ShipType.Model
    name: str
    description: str
    supply: SupplyLevel.Model
    activity: Optional[ActivityLevel.Model] = None
    purchasePrice: int
    frame: ShipFrame.Model
    reactor: ShipReactor.Model
    engine: ShipEngine.Model
    modules: List[ShipModule.Model]
    mounts: List[ShipMount.Model]
    crew: Crew
