# generated by datamodel-codegen:
#   filename:  ShipNavRoute.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field

from . import ShipNavRouteWaypoint


class Model(BaseModel):
    destination: ShipNavRouteWaypoint.Model
    origin: ShipNavRouteWaypoint.Model
    departureTime: AwareDatetime = Field(
        ..., description="The date time of the ship's departure."
    )
    arrival: AwareDatetime = Field(
        ...,
        description="The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.",
    )
