# generated by datamodel-codegen:
#   filename:  ShipNavRouteWaypointDeprecated.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr

from .SystemSymbol import SystemSymbol
from .WaypointType import WaypointType


class ShipNavRouteWaypointDeprecated(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description="The symbol of the waypoint."
    )
    type: WaypointType
    systemSymbol: SystemSymbol
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
