# generated by datamodel-codegen:
#   filename:  ShipNavFlightMode.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from enum import Enum


class ShipNavFlightMode(Enum):
    DRIFT = "DRIFT"
    STEALTH = "STEALTH"
    CRUISE = "CRUISE"
    BURN = "BURN"
