# generated by datamodel-codegen:
#   filename:  Ship.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from . import (
    Cooldown,
    ShipCargo,
    ShipCrew,
    ShipEngine,
    ShipFrame,
    ShipFuel,
    ShipModule,
    ShipMount,
    ShipNav,
    ShipReactor,
    ShipRegistration,
)


class Model(BaseModel):
    symbol: str = Field(
        ...,
        description="The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`",
    )
    registration: ShipRegistration.Model
    nav: ShipNav.Model
    crew: ShipCrew.Model
    frame: ShipFrame.Model
    reactor: ShipReactor.Model
    engine: ShipEngine.Model
    cooldown: Cooldown.Model
    modules: List[ShipModule.Model] = Field(
        ..., description="Modules installed in this ship."
    )
    mounts: List[ShipMount.Model] = Field(
        ..., description="Mounts installed in this ship."
    )
    cargo: ShipCargo.Model
    fuel: ShipFuel.Model
