# generated by datamodel-codegen:
#   filename:  ShipComponentIntegrity.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import Field, RootModel, confloat


class ShipComponentIntegrity(RootModel[confloat(ge=0.0, le=1.0)]):
    root: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description="The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.",
        title="ShipComponentIntegrity",
    )
