# generated by datamodel-codegen:
#   filename:  ShipModificationTransaction.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field, conint


class Model(BaseModel):
    waypointSymbol: str = Field(
        ...,
        description="The symbol of the waypoint where the transaction took place.",
    )
    shipSymbol: str = Field(
        ..., description="The symbol of the ship that made the transaction."
    )
    tradeSymbol: str = Field(..., description="The symbol of the trade good.")
    totalPrice: conint(ge=0) = Field(
        ..., description="The total price of the transaction."
    )
    timestamp: AwareDatetime = Field(
        ..., description="The timestamp of the transaction."
    )
