# generated by datamodel-codegen:
#   filename:  ShipNavStatus.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from enum import Enum


class ShipNavStatus(Enum):
    IN_TRANSIT = "IN_TRANSIT"
    IN_ORBIT = "IN_ORBIT"
    DOCKED = "DOCKED"
