# generated by datamodel-codegen:
#   filename:  ShipCrew.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, conint


class Rotation(Enum):
    STRICT = "STRICT"
    RELAXED = "RELAXED"


class ShipCrew(BaseModel):
    current: int = Field(
        ..., description="The current number of crew members on the ship."
    )
    required: int = Field(
        ...,
        description="The minimum number of crew members required to maintain the ship.",
    )
    capacity: int = Field(
        ...,
        description="The maximum number of crew members the ship can support.",
    )
    rotation: Rotation = Field(
        ...,
        description="The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.",
    )
    morale: conint(ge=0, le=100) = Field(
        ...,
        description="A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.",
    )
    wages: conint(ge=0) = Field(
        ...,
        description="The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.",
    )
