# generated by datamodel-codegen:
#   filename:  ShipCargo.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, conint

from . import ShipCargoItem


class Model(BaseModel):
    capacity: conint(ge=0) = Field(
        ...,
        description="The max number of items that can be stored in the cargo hold.",
    )
    units: conint(ge=0) = Field(
        ...,
        description="The number of items currently stored in the cargo hold.",
    )
    inventory: List[ShipCargoItem.Model] = Field(
        ..., description="The items currently in the cargo hold."
    )
