# generated by datamodel-codegen:
#   filename:  ShipNav.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel

from .ShipNavFlightMode import ShipNavFlightMode
from .ShipNavRoute import ShipNavRoute
from .ShipNavStatus import ShipNavStatus
from .SystemSymbol import SystemSymbol
from .WaypointSymbol import WaypointSymbol


class ShipNav(BaseModel):
    systemSymbol: SystemSymbol
    waypointSymbol: WaypointSymbol
    route: ShipNavRoute
    status: ShipNavStatus
    flightMode: ShipNavFlightMode
