# generated by datamodel-codegen:
#   filename:  SiphonYield.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from .TradeSymbol import TradeSymbol


class SiphonYield(BaseModel):
    symbol: TradeSymbol
    units: int = Field(
        ...,
        description="The number of units siphoned that were placed into the ship's cargo hold.",
    )
