# generated by datamodel-codegen:
#   filename:  SupplyLevel.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from enum import Enum


class Model(Enum):
    SCARCE = "SCARCE"
    LIMITED = "LIMITED"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    ABUNDANT = "ABUNDANT"
