# generated by datamodel-codegen:
#   filename:  SurveyDeposit.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SurveyDeposit(BaseModel):
    symbol: str = Field(..., description="The symbol of the deposit.")
