# generated by datamodel-codegen:
#   filename:  SurveyDeposit.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    symbol: str = Field(..., description="The symbol of the deposit.")
