# generated by datamodel-codegen:
#   filename:  SystemFaction.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import FactionSymbol


class Model(BaseModel):
    symbol: FactionSymbol.Model
