# generated by datamodel-codegen:
#   filename:  SystemWaypoint.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr

from . import WaypointOrbital, WaypointSymbol, WaypointType


class Model(BaseModel):
    symbol: WaypointSymbol.Model
    type: WaypointType.Model
    x: int = Field(
        ...,
        description="Relative position of the waypoint on the system's x axis. This is not an absolute position in the universe.",
    )
    y: int = Field(
        ...,
        description="Relative position of the waypoint on the system's y axis. This is not an absolute position in the universe.",
    )
    orbitals: List[WaypointOrbital.Model] = Field(
        ..., description="Waypoints that orbit this waypoint."
    )
    orbits: Optional[constr(min_length=1)] = Field(
        None,
        description="The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.",
    )
