# generated by datamodel-codegen:
#   filename:  System.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr

from . import SystemFaction, SystemType, SystemWaypoint


class Model(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description="The symbol of the system."
    )
    sectorSymbol: constr(min_length=1) = Field(
        ..., description="The symbol of the sector."
    )
    constellation: Optional[str] = Field(
        None, description="The constellation that the system is part of."
    )
    name: Optional[str] = Field(None, description="The name of the system.")
    type: SystemType.Model
    x: int = Field(
        ...,
        description="Relative position of the system in the sector in the x axis.",
    )
    y: int = Field(
        ...,
        description="Relative position of the system in the sector in the y axis.",
    )
    waypoints: List[SystemWaypoint.Model] = Field(
        ..., description="Waypoints in this system."
    )
    factions: List[SystemFaction.Model] = Field(
        ..., description="Factions that control this system."
    )
