# generated by datamodel-codegen:
#   filename:  SystemFaction.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import FactionSymbol


class SystemFaction(BaseModel):
    symbol: FactionSymbol
