# generated by datamodel-codegen:
#   filename:  SystemSymbol.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import Field, RootModel, constr


class SystemSymbol(RootModel[constr(min_length=1)]):
    root: constr(min_length=1) = Field(
        ..., description="The symbol of the system.", title="SystemSymbol"
    )
