# generated by datamodel-codegen:
#   filename:  SystemFaction.json
#   timestamp: 2025-10-21T07:43:52+00:00

from __future__ import annotations

from pydantic import BaseModel

from .FactionSymbol import FactionSymbol


class SystemFaction(BaseModel):
    symbol: FactionSymbol
