# generated by datamodel-codegen:
#   filename:  TradeGood.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import TradeSymbol


class Model(BaseModel):
    symbol: TradeSymbol.Model
    name: str = Field(..., description="The name of the good.")
    description: str = Field(..., description="The description of the good.")
