# generated by datamodel-codegen:
#   filename:  TradeGood.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import TradeSymbol


class TradeGood(BaseModel):
    symbol: TradeSymbol
    name: str = Field(..., description="The name of the good.")
    description: str = Field(..., description="The description of the good.")
