# generated by datamodel-codegen:
#   filename:  WaypointOrbital.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class WaypointOrbital(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description="The symbol of the orbiting waypoint."
    )
