# generated by datamodel-codegen:
#   filename:  WaypointTrait.json
#   timestamp: 2025-10-20T08:56:39+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import WaypointTraitSymbol


class WaypointTrait(BaseModel):
    symbol: WaypointTraitSymbol
    name: str = Field(..., description="The name of the trait.")
    description: str = Field(..., description="A description of the trait.")
