# generated by datamodel-codegen:
#   filename:  WaypointModifier.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import WaypointModifierSymbol


class Model(BaseModel):
    symbol: WaypointModifierSymbol.Model
    name: str = Field(..., description="The name of the trait.")
    description: str = Field(..., description="A description of the trait.")
