# generated by datamodel-codegen:
#   filename:  WaypointModifierSymbol.json
#   timestamp: 2025-10-20T08:16:07+00:00

from __future__ import annotations

from enum import Enum


class Model(Enum):
    STRIPPED = "STRIPPED"
    UNSTABLE = "UNSTABLE"
    RADIATION_LEAK = "RADIATION_LEAK"
    CRITICAL_LIMIT = "CRITICAL_LIMIT"
    CIVIL_UNREST = "CIVIL_UNREST"
