# generated by datamodel-codegen:
#   filename:  WaypointSymbol.json
#   timestamp: 2025-10-09T06:51:20+00:00

from __future__ import annotations

from pydantic import Field, RootModel, constr


class Model(RootModel[constr(min_length=1)]):
    root: constr(min_length=1) = Field(
        ..., description="The symbol of the waypoint."
    )
